from dataclasses import dataclass
from typing import Optional
from uuid import UUID
from datetime import date

@dataclass
class NFModelEntrada:
    recnum: Optional[int] = None
    filial: Optional[int] = None
    pedido: Optional[int] = None
    fornecedor: Optional[int] = None
    nota_fiscal: Optional[int] = None
    modelo: Optional[str] = None
    serie: Optional[str] = None
    serie_nf: Optional[str] = None
    comprador: Optional[int] = None
    dt_emissao: Optional[date] = None
    dt_entrada: Optional[date] = None
    transacao: Optional[int] = None
    operacao: Optional[int] = None
    centro_custo: Optional[int] = None
    cnpj: Optional[str] = None
    inscricao: Optional[str] = None
    frete_pg: Optional[str] = None
    vr_produtos: Optional[float] = None
    vr_total: Optional[float] = None
    vr_frete: Optional[float] = None
    icmsfrete: Optional[float] = None
    ipifrete: Optional[float] = None
    vr_icmsfrete: Optional[float] = None
    vr_ipifrete: Optional[float] = None
    vr_descontos: Optional[float] = None
    vr_despesas: Optional[float] = None
    vr_encargos: Optional[float] = None
    vr_ipi: Optional[float] = None
    vr_baseicms: Optional[float] = None
    vr_icms: Optional[float] = None
    vr_basesubst: Optional[float] = None
    vr_icmsubst: Optional[float] = None
    vr_seguro: Optional[float] = None
    vr_embalagem: Optional[float] = None
    icmsembalagem: Optional[float] = None
    ipiembalagem: Optional[float] = None
    vr_icmsembal: Optional[float] = None
    vr_ipiembal: Optional[float] = None
    vr_descarga: Optional[float] = None
    vr_servico: Optional[float] = None
    vr_baseiss: Optional[float] = None
    vr_iss: Optional[float] = None
    fatura: Optional[str] = None
    itens: Optional[int] = None
    conta_caixa: Optional[int] = None
    banco: Optional[int] = None
    transportadora: Optional[int] = None
    conhecimento: Optional[int] = None
    dt_emissaof: Optional[date] = None
    dt_vencimentof: Optional[date] = None
    vr_fretef: Optional[float] = None
    vr_icmsf: Optional[float] = None
    vr_freteratear: Optional[float] = None
    vr_baseicmsf: Optional[float] = None
    vr_icmsfratear: Optional[float] = None
    cfop_fratear: Optional[float] = None
    vr_dinheiro: Optional[float] = None
    vr_prazo: Optional[float] = None
    vr_cheque: Optional[float] = None
    vr_chequepre: Optional[float] = None
    vr_cartao: Optional[float] = None
    vr_electron: Optional[float] = None
    vr_outros: Optional[float] = None
    vr_antecipado: Optional[float] = None
    sequencia: Optional[int] = None
    observacao: Optional[str] = None
    foto: Optional[str] = None
    impresso: Optional[str] = None
    fechado: Optional[str] = None
    compensar_chq: Optional[str] = None
    digitar_serial: Optional[str] = None
    status_fornec: Optional[str] = None
    status_transp: Optional[str] = None
    tmp_vrtotal: Optional[float] = None
    data_inc: Optional[date] = None
    data_alt: Optional[date] = None
    data_exc: Optional[date] = None
    hora_inc: Optional[str] = None
    hora_alt: Optional[str] = None
    hora_exc: Optional[str] = None
    usu_inc: Optional[int] = None
    usu_alt: Optional[int] = None
    usu_exc: Optional[int] = None
    maq_inc: Optional[str] = None
    maq_alt: Optional[str] = None
    maq_exc: Optional[str] = None
    envia_pocket: Optional[str] = None
    dtexportacao: Optional[date] = None
    xml_nfe: Optional[str] = None
    desc_condic: Optional[str] = None
    modelo_ctrc: Optional[str] = None
    serie_ctrc: Optional[str] = None
    chave_nfe: Optional[str] = None
    vr_pis_st: Optional[float] = None
    vr_cofins_st: Optional[float] = None
    chave_cte: Optional[str] = None
    tp_cte: Optional[str] = None
    vr_servico_ct: Optional[float] = None
    vr_desconto_ct: Optional[float] = None
    vr_outros_ct: Optional[float] = None
    vr_isento_ct: Optional[float] = None
    aliq_icms_ct: Optional[float] = None
    vr_pis: Optional[float] = None
    vr_cofins: Optional[float] = None
    cst_ct: Optional[str] = None
    vr_redicms_ct: Optional[float] = None
    id_cadcon: Optional[int] = None
    vr_recsubst: Optional[float] = None
    digita_lote: Optional[str] = None
    vr_deson: Optional[float] = None
    portador: Optional[int] = None
    situacao_doc: Optional[str] = None
    status_conferencia: Optional[str] = None
    id: Optional[UUID] = None
    regime_trib: Optional[str] = None
    recnum_2: Optional[int] = None
    filial_2: Optional[str] = None
    pedido_2: Optional[str] = None
    fornecedor_2: Optional[str] = None
    nota_fiscal_2: Optional[str] = None
    modelo_2: Optional[str] = None
    serie_2: Optional[str] = None
    item: Optional[str] = None
    sequencia_2: Optional[str] = None
    operacao_2: Optional[str] = None
    matricula: Optional[str] = None
    qtd_entrada: Optional[float] = None
    qtd_transferida: Optional[float] = None
    qtd_compra: Optional[float] = None
    und_compra: Optional[str] = None
    vr_base: Optional[float] = None
    vr_entrada: Optional[float] = None
    vr_desconto: Optional[float] = None
    vr_total_2: Optional[float] = None
    vr_custo: Optional[float] = None
    vr_custozero: Optional[float] = None
    markup: Optional[float] = None
    lucro: Optional[float] = None
    vr_venda: Optional[float] = None
    icms: Optional[float] = None
    ipi: Optional[float] = None
    substituicao: Optional[float] = None
    reducao: Optional[float] = None
    cst: Optional[str] = None
    dt_entrada_2: Optional[str] = None
    utiliza_serial: Optional[str] = None
    fechado_2: Optional[str] = None
    desp_ipi: Optional[float] = None
    desp_frete: Optional[float] = None
    desp_encargos: Optional[float] = None
    desp_subst: Optional[float] = None
    desp_ipifrete: Optional[float] = None
    desp_icmsfrete: Optional[float] = None
    desp_desconto: Optional[float] = None
    desp_embalagem: Optional[float] = None
    desp_icmsembal: Optional[float] = None
    desp_ipiembal: Optional[float] = None
    desp_iss: Optional[float] = None
    cfop: Optional[str] = None
    data_inc_2: Optional[str] = None
    data_alt_2: Optional[str] = None
    data_exc_2: Optional[str] = None
    hora_inc_2: Optional[str] = None
    hora_alt_2: Optional[str] = None
    hora_exc_2: Optional[str] = None
    usu_inc_2: Optional[str] = None
    usu_alt_2: Optional[str] = None
    usu_exc_2: Optional[str] = None
    maq_inc_2: Optional[str] = None
    maq_alt_2: Optional[str] = None
    maq_exc_2: Optional[str] = None
    envia_pocket_2: Optional[str] = None
    dtexportacao_2: Optional[str] = None
    cst_ipi: Optional[str] = None
    ipi_unidade: Optional[float] = None
    vr_baseipi: Optional[float] = None
    cst_pis: Optional[str] = None
    vr_basepis: Optional[float] = None
    vr_basecofins: Optional[float] = None
    aliq_pis: Optional[float] = None
    aliq_cofins: Optional[float] = None
    vr_pis_2: Optional[float] = None
    vr_cofins_2: Optional[float] = None
    icms_padrao_uf: Optional[str] = None
    vr_baseicms_2: Optional[float] = None
    vr_icms_2: Optional[float] = None
    vr_basesubst_2: Optional[float] = None
    vr_icmsseguro: Optional[float] = None
    vr_icmsfrete_2: Optional[float] = None
    desp_pis_st: Optional[float] = None
    desp_cofins_st: Optional[float] = None
    vr_reducaoicms: Optional[float] = None
    desc_condic_2: Optional[str] = None
    usa_baseicms: Optional[str] = None
    nat_bc_pis: Optional[str] = None
    xml_nfe_2: Optional[str] = None
    limite_desca: Optional[float] = None
    limite_descv: Optional[float] = None
    vr_minimoa: Optional[float] = None
    vr_minimov: Optional[float] = None
    desp_recsubst: Optional[float] = None
    al_cred_antec: Optional[float] = None
    vr_cred_antec: Optional[float] = None
    desp_deson: Optional[float] = None
    temp_qtentrega: Optional[float] = None
    ultimo_conferido: Optional[str] = None
    id_2: Optional[int] = None
    vr_custozeroa: Optional[float] = None
    lucroa: Optional[float] = None
    markupa: Optional[float] = None
    vr_vendaa: Optional[float] = None
    qtd_tributavel: Optional[float] = None
    adrem_icms: Optional[float] = None
    vricms_monofasico: Optional[float] = None
    qtd_tributavelretencao: Optional[float] = None
    adrem_icmsretencao: Optional[float] = None
    vricms_monoretencao: Optional[float] = None
    recnum_3: Optional[int] = None
    matricula_2: Optional[str] = None
    tipo: Optional[str] = None
    fornecedor_3: Optional[str] = None
    marca: Optional[str] = None
    grupo: Optional[str] = None
    cod_remarcacao: Optional[str] = None
    descricao: Optional[str] = None
    desc_fabrica: Optional[str] = None
    referencia: Optional[str] = None
    unidade: Optional[str] = None
    grade_padrao: Optional[str] = None
    codigo_fiscal: Optional[str] = None
    codigo_barra: Optional[str] = None
    status: Optional[str] = None
    peso: Optional[float] = None
    unidade_compra: Optional[str] = None
    ipi_compra: Optional[float] = None
    subst_compra: Optional[float] = None
    icms_compra: Optional[float] = None
    cst_compra: Optional[str] = None
    editar: Optional[str] = None
    aplicacao: Optional[str] = None
    observacao_2: Optional[str] = None
    imprime_codbar: Optional[str] = None
    imprime_etiq: Optional[str] = None
    imprime_tabela: Optional[str] = None
    desconto_ok: Optional[str] = None
    utiliza_balanca: Optional[str] = None
    suspensa: Optional[str] = None
    custo_adicional: Optional[float] = None
    foto_2: Optional[str] = None
    tmp_codbarra: Optional[str] = None
    cod_enq_ipi: Optional[str] = None
    data_inc_3: Optional[str] = None
    hora_inc_3: Optional[str] = None
    usu_inc_3: Optional[str] = None
    maq_inc_3: Optional[str] = None
    data_alt_3: Optional[str] = None
    hora_alt_3: Optional[str] = None
    usu_alt_3: Optional[str] = None
    maq_alt_3: Optional[str] = None
    envia_pocket_3: Optional[str] = None
    dtexportacao_3: Optional[str] = None
    sped_1400: Optional[str] = None
    tipo_item: Optional[str] = None
    codigo_ex_tipi: Optional[str] = None
    ipi_unid_compra: Optional[float] = None
    reducao_compra: Optional[float] = None
    validade: Optional[str] = None
    codigo_anp: Optional[str] = None
    composicao: Optional[str] = None
    ativ_cont_prev: Optional[str] = None
    compos_prod: Optional[str] = None
    pais_origem: Optional[str] = None
    largura: Optional[float] = None
    rendimento: Optional[float] = None
    imagens: Optional[str] = None
    al_tributos: Optional[float] = None
    ippt: Optional[str] = None
    codigo_fci: Optional[str] = None
    unidade_entrega: Optional[str] = None
    codigo_imp: Optional[str] = None
    desc_adicional: Optional[str] = None
    codigo_cest: Optional[str] = None
    mva_padrao: Optional[float] = None
    usa_lote: Optional[str] = None
    altura: Optional[float] = None
    comprimento: Optional[float] = None
    cta_contabil: Optional[str] = None
    calcula_fem: Optional[str] = None
    calcula_fcp: Optional[str] = None
    perc_glp: Optional[float] = None
    perc_gnimp: Optional[float] = None
    perc_gnnac: Optional[float] = None
    vr_partida: Optional[float] = None
    id_edicao: Optional[int] = None
    calcular_fcp_st: Optional[str] = None
    codigo_anvisa: Optional[str] = None
    motivo_isencao: Optional[str] = None
    ean_tributavel: Optional[str] = None
    qtd_embalagem: Optional[float] = None

    @classmethod
    def from_raw_data(cls, file: dict):
        return cls(
        recnum = file.get("recnum"),
        filial = file.get("filial"),
        pedido = file.get("pedido"),
        fornecedor = file.get("fornecedor"),
        nota_fiscal = file.get("nota_fiscal"),
        modelo= file.get("modelo"),
        serie= file.get("serie"),
        serie_nf= file.get("serie_nf"),
        comprador = file.get("comprador"),
        dt_emissao = file.get("dt_emissao"),
        dt_entrada = file.get("dt_entrada"),
        transacao = file.get("transacao"),
        operacao = file.get("operacao"),
        centro_custo = file.get("centro_custo"),
        cnpj= file.get("cnpj"),
        inscricao= file.get("inscricao"),
        frete_pg= file.get("frete_pg"),
        vr_produtos = file.get("vr_produtos"),
        vr_total = file.get("vr_total"),
        vr_frete = file.get("vr_frete"),
        icmsfrete = file.get("icmsfrete"),
        ipifrete = file.get("ipifrete"),
        vr_icmsfrete = file.get("vr_icmsfrete"),
        vr_ipifrete = file.get("vr_ipifrete"),
        vr_descontos = file.get("vr_descontos"),
        vr_despesas = file.get("vr_despesas"),
        vr_encargos = file.get("vr_encargos"),
        vr_ipi = file.get("vr_ipi"),
        vr_baseicms = file.get("vr_baseicms"),
        vr_icms = file.get("vr_icms"),
        vr_basesubst = file.get("vr_basesubst"),
        vr_icmsubst = file.get("vr_icmsubst"),
        vr_seguro = file.get("vr_seguro"),
        vr_embalagem = file.get("vr_embalagem"),
        icmsembalagem = file.get("icmsembalagem"),
        ipiembalagem = file.get("ipiembalagem"),
        vr_icmsembal = file.get("vr_icmsembal"),
        vr_ipiembal = file.get("vr_ipiembal"),
        vr_descarga = file.get("vr_descarga"),
        vr_servico = file.get("vr_servico"),
        vr_baseiss = file.get("vr_baseiss"),
        vr_iss = file.get("vr_iss"),
        fatura= file.get("fatura"),
        itens = file.get("itens"),
        conta_caixa = file.get("conta_caixa"),
        banco = file.get("banco"),
        transportadora = file.get("transportadora"),
        conhecimento = file.get("conhecimento"),
        dt_emissaof = file.get("dt_emissaof"),
        dt_vencimentof = file.get("dt_vencimentof"),
        vr_fretef = file.get("vr_fretef"),
        vr_icmsf = file.get("vr_icmsf"),
        vr_freteratear = file.get("vr_freteratear"),
        vr_baseicmsf = file.get("vr_baseicmsf"),
        vr_icmsfratear = file.get("vr_icmsfratear"),
        cfop_fratear = file.get("cfop_fratear"),
        vr_dinheiro = file.get("vr_dinheiro"),
        vr_prazo = file.get("vr_prazo"),
        vr_cheque = file.get("vr_cheque"),
        vr_chequepre = file.get("vr_chequepre"),
        vr_cartao = file.get("vr_cartao"),
        vr_electron = file.get("vr_electron"),
        vr_outros = file.get("vr_outros"),
        vr_antecipado = file.get("vr_antecipado"),
        sequencia = file.get("sequencia"),
        observacao= file.get("observacao"),
        foto= file.get("foto"),
        impresso= file.get("impresso"),
        fechado= file.get("fechado"),
        compensar_chq= file.get("compensar_chq"),
        digitar_serial= file.get("digitar_serial"),
        status_fornec= file.get("status_fornec"),
        status_transp= file.get("status_transp"),
        tmp_vrtotal = file.get("tmp_vrtotal"),
        data_inc = file.get("data_inc"),
        data_alt = file.get("data_alt"),
        data_exc = file.get("data_exc"),
        hora_inc= file.get("hora_inc"),
        hora_alt= file.get("hora_alt"),
        hora_exc= file.get("hora_exc"),
        usu_inc = file.get("usu_inc"),
        usu_alt = file.get("usu_alt"),
        usu_exc = file.get("usu_exc"),
        maq_inc= file.get("maq_inc"),
        maq_alt= file.get("maq_alt"),
        maq_exc= file.get("maq_exc"),
        envia_pocket= file.get("envia_pocket"),
        dtexportacao = file.get("dtexportacao"),
        xml_nfe= file.get("xml_nfe"),
        desc_condic= file.get("desc_condic"),
        modelo_ctrc= file.get("modelo_ctrc"),
        serie_ctrc= file.get("serie_ctrc"),
        chave_nfe= file.get("chave_nfe"),
        vr_pis_st = file.get("vr_pis_st"),
        vr_cofins_st = file.get("vr_cofins_st"),
        chave_cte= file.get("chave_cte"),
        tp_cte= file.get("tp_cte"),
        vr_servico_ct = file.get("vr_servico_ct"),
        vr_desconto_ct = file.get("vr_desconto_ct"),
        vr_outros_ct = file.get("vr_outros_ct"),
        vr_isento_ct = file.get("vr_isento_ct"),
        aliq_icms_ct = file.get("aliq_icms_ct"),
        vr_pis = file.get("vr_pis"),
        vr_cofins = file.get("vr_cofins"),
        cst_ct= file.get("cst_ct"),
        vr_redicms_ct = file.get("vr_redicms_ct"),
        id_cadcon = file.get("id_cadcon"),
        vr_recsubst = file.get("vr_recsubst"),
        digita_lote= file.get("digita_lote"),
        vr_deson = file.get("vr_deson"),
        portador = file.get("portador"),
        situacao_doc= file.get("situacao_doc"),
        status_conferencia= file.get("status_conferencia"),
        id = file.get("id"),
        regime_trib= file.get("regime_trib"),
        recnum_2 = file.get("recnum_2"),
        filial_2= file.get("filial_2"),
        pedido_2= file.get("pedido_2"),
        fornecedor_2= file.get("fornecedor_2"),
        nota_fiscal_2= file.get("nota_fiscal_2"),
        modelo_2= file.get("modelo_2"),
        serie_2= file.get("serie_2"),
        item= file.get("item"),
        sequencia_2= file.get("sequencia_2"),
        operacao_2= file.get("operacao_2"),
        matricula= file.get("matricula"),
        qtd_entrada = file.get("qtd_entrada"),
        qtd_transferida = file.get("qtd_transferida"),
        qtd_compra = file.get("qtd_compra"),
        und_compra= file.get("und_compra"),
        vr_base = file.get("vr_base"),
        vr_entrada = file.get("vr_entrada"),
        vr_desconto = file.get("vr_desconto"),
        vr_total_2 = file.get("vr_total_2"),
        vr_custo = file.get("vr_custo"),
        vr_custozero = file.get("vr_custozero"),
        markup = file.get("markup"),
        lucro = file.get("lucro"),
        vr_venda = file.get("vr_venda"),
        icms = file.get("icms"),
        ipi = file.get("ipi"),
        substituicao = file.get("substituicao"),
        reducao = file.get("reducao"),
        cst= file.get("cst"),
        dt_entrada_2= file.get("dt_entrada_2"),
        utiliza_serial= file.get("utiliza_serial"),
        fechado_2= file.get("fechado_2"),
        desp_ipi = file.get("desp_ipi"),
        desp_frete = file.get("desp_frete"),
        desp_encargos = file.get("desp_encargos"),
        desp_subst = file.get("desp_subst"),
        desp_ipifrete = file.get("desp_ipifrete"),
        desp_icmsfrete = file.get("desp_icmsfrete"),
        desp_desconto = file.get("desp_desconto"),
        desp_embalagem = file.get("desp_embalagem"),
        desp_icmsembal = file.get("desp_icmsembal"),
        desp_ipiembal = file.get("desp_ipiembal"),
        desp_iss = file.get("desp_iss"),
        cfop= file.get("cfop"),
        data_inc_2= file.get("data_inc_2"),
        data_alt_2= file.get("data_alt_2"),
        data_exc_2= file.get("data_exc_2"),
        hora_inc_2= file.get("hora_inc_2"),
        hora_alt_2= file.get("hora_alt_2"),
        hora_exc_2= file.get("hora_exc_2"),
        usu_inc_2= file.get("usu_inc_2"),
        usu_alt_2= file.get("usu_alt_2"),
        usu_exc_2= file.get("usu_exc_2"),
        maq_inc_2= file.get("maq_inc_2"),
        maq_alt_2= file.get("maq_alt_2"),
        maq_exc_2= file.get("maq_exc_2"),
        envia_pocket_2= file.get("envia_pocket_2"),
        dtexportacao_2= file.get("dtexportacao_2"),
        cst_ipi= file.get("cst_ipi"),
        ipi_unidade = file.get("ipi_unidade"),
        vr_baseipi = file.get("vr_baseipi"),
        cst_pis= file.get("cst_pis"),
        vr_basepis = file.get("vr_basepis"),
        vr_basecofins = file.get("vr_basecofins"),
        aliq_pis = file.get("aliq_pis"),
        aliq_cofins = file.get("aliq_cofins"),
        vr_pis_2 = file.get("vr_pis_2"),
        vr_cofins_2 = file.get("vr_cofins_2"),
        icms_padrao_uf= file.get("icms_padrao_uf"),
        vr_baseicms_2 = file.get("vr_baseicms_2"),
        vr_icms_2 = file.get("vr_icms_2"),
        vr_cred_antec = file.get("vr_cred_antec"),
        desp_deson = file.get("desp_deson"),
        temp_qtentrega = file.get("temp_qtentrega"),
        ultimo_conferido= file.get("ultimo_conferido"),
        id_2 = file.get("id_2"),
        vr_custozeroa = file.get("vr_custozeroa"),
        lucroa = file.get("lucroa"),
        markupa = file.get("markupa"),
        vr_vendaa = file.get("vr_vendaa"),
        qtd_tributavel = file.get("qtd_tributavel"),
        adrem_icms = file.get("adrem_icms"),
        vricms_monofasico = file.get("vricms_monofasico"),
        qtd_tributavelretencao = file.get("qtd_tributavelretencao"),
        adrem_icmsretencao = file.get("adrem_icmsretencao"),
        vricms_monoretencao = file.get("vricms_monoretencao"),
        recnum_3 = file.get("recnum_3"),
        matricula_2= file.get("matricula_2"),
        tipo= file.get("tipo"),
        fornecedor_3= file.get("fornecedor_3"),
        marca= file.get("marca"),
        grupo= file.get("grupo"),
        cod_remarcacao= file.get("cod_remarcacao"),
        descricao= file.get("descricao"),
        desc_fabrica= file.get("desc_fabrica"),
        referencia= file.get("referencia"),
        unidade= file.get("unidade"),
        grade_padrao= file.get("grade_padrao"),
        codigo_fiscal= file.get("codigo_fiscal"),
        codigo_barra= file.get("codigo_barra"),
        status= file.get("status"),
        peso = file.get("peso"),
        unidade_compra= file.get("unidade_compra"),
        ipi_compra = file.get("ipi_compra"),
        subst_compra = file.get("subst_compra"),
        icms_compra = file.get("icms_compra"),
        cst_compra= file.get("cst_compra"),
        editar= file.get("editar"),
        aplicacao= file.get("aplicacao"),
        observacao_2= file.get("observacao_2"),
        imprime_codbar= file.get("imprime_codbar"),
        imprime_etiq= file.get("imprime_etiq"),
        imprime_tabela= file.get("imprime_tabela"),
        desconto_ok= file.get("desconto_ok"),
        utiliza_balanca= file.get("utiliza_balanca"),
        suspensa= file.get("suspensa"),
        custo_adicional = file.get("custo_adicional"),
        foto_2= file.get("foto_2"),
        tmp_codbarra= file.get("tmp_codbarra"),
        cod_enq_ipi= file.get("cod_enq_ipi"),
        data_inc_3= file.get("data_inc_3"),
        hora_inc_3= file.get("hora_inc_3"),
        usu_inc_3= file.get("usu_inc_3"),
        maq_inc_3= file.get("maq_inc_3"),
        data_alt_3= file.get("data_alt_3"),
        hora_alt_3= file.get("hora_alt_3"),
        usu_alt_3= file.get("usu_alt_3"),
        maq_alt_3= file.get("maq_alt_3"),
        envia_pocket_3= file.get("envia_pocket_3"),
        dtexportacao_3= file.get("dtexportacao_3"),
        sped_1400= file.get("sped_1400"),
        tipo_item= file.get("tipo_item"),
        codigo_ex_tipi= file.get("codigo_ex_tipi"),
        ipi_unid_compra = file.get("ipi_unid_compra"),
        reducao_compra = file.get("reducao_compra"),
        validade= file.get("validade"),
        codigo_anp= file.get("codigo_anp"),
        composicao= file.get("composicao"),
        ativ_cont_prev= file.get("ativ_cont_prev"),
        compos_prod= file.get("compos_prod"),
        pais_origem= file.get("pais_origem"),
        largura = file.get("largura"),
        rendimento = file.get("rendimento"),
        imagens= file.get("imagens"),
        al_tributos = file.get("al_tributos"),
        ippt= file.get("ippt"),
        codigo_fci= file.get("codigo_fci"),
        unidade_entrega= file.get("unidade_entrega"),
        codigo_imp= file.get("codigo_imp"),
        desc_adicional= file.get("desc_adicional"),
        codigo_cest= file.get("codigo_cest"),
        mva_padrao = file.get("mva_padrao"),
        usa_lote= file.get("usa_lote"),
        altura = file.get("altura"),
        comprimento = file.get("comprimento"),
        cta_contabil= file.get("cta_contabil"),
        calcula_fem= file.get("calcula_fem"),
        calcula_fcp= file.get("calcula_fcp"),
        perc_glp = file.get("perc_glp"),
        perc_gnimp = file.get("perc_gnimp"),
        perc_gnnac = file.get("perc_gnnac"),
        vr_partida = file.get("vr_partida"),
        id_edicao = file.get("id_edicao"),
        calcular_fcp_st= file.get("calcular_fcp_st"),
        codigo_anvisa= file.get("codigo_anvisa"),
        motivo_isencao= file.get("motivo_isencao"),
        ean_tributavel= file.get("ean_tributavel"),
        qtd_embalagem = file.get("qtd_embalagem"),
        )